version: '3.7'

services:
  mysql:
    image: "mariadb:10.3.35"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=root
      - DOCKER_GATEWAY_HOST:DOCKER_GATEWAY_HOST
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
volumes:
  mysql-data: